[package]
name = "syndromes"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ariadne = "0.6"
logic_simulation = { path = "../logic_simulation" }
ndarray.workspace = true
ndarray-npy = "0.10"
rand.workspace = true
rand_distr = "0.6"
thiserror.workspace = true
